Repository team-codebrewers/QuotesRestAPI, pull requests merged in 2021-11, with the labels that each got.

#10 Added request verification
  src/main/java/com/example/quotesrestapi/authentication/AuthServiceConfig.java
  src/main/java/com/example/quotesrestapi/contoller/AuthController.java
  src/main/java/com/example/quotesrestapi/contoller/QuoteAPIController.java
Labels: enhancement

#11 added getters and setters
  src/main/java/com/example/quotesrestapi/model/Quote.java
Labels: good first issue

#12 Divided Task
  src/main/java/com/example/quotesrestapi/authentication/AuthServiceConfig.java
  src/main/java/com/example/quotesrestapi/contoller/AuthController.java
  src/main/java/com/example/quotesrestapi/contoller/QuoteAPIController.java
  src/test/java/com/example/quotesrestapi/DatabaseTests.java
  src/test/java/com/example/quotesrestapi/QuoteAPIFunctionTest.java
Labels: enhancement

#14 Added toking issue api call.
  src/main/java/com/example/quotesrestapi/contoller/AuthController.java
  src/main/java/com/example/quotesrestapi/model/User.java
Labels: features
