Repository team-codebrewers/QuotesRestAPI, pull requests merged in 2021-12, with the labels that each got.

#15 completed_todo
  src/main/java/com/example/quotesrestapi/contoller/QuoteAPIController.java
  src/test/java/com/example/quotesrestapi/QuoteAPIFunctionTest.java
Labels: features

#16 Minor changes
  src/main/java/com/example/quotesrestapi/QuotesRestapiApplication.java
  src/main/java/com/example/quotesrestapi/authentication/AuthServiceConfig.java
  src/main/java/com/example/quotesrestapi/contoller/QuoteAPIController.java
  src/main/java/com/example/quotesrestapi/model/Quote.java
  src/main/java/com/example/quotesrestapi/model/SuperUser.java
  src/main/java/com/example/quotesrestapi/model/User.java
  src/main/java/com/example/quotesrestapi/services/DatabaseService.java
  src/test/java/com/example/quotesrestapi/QuoteAPIFunctionTest.java
  src/test/java/com/example/quotesrestapi/QuoteTests.java
  src/test/java/com/example/quotesrestapi/QuotesRestapiApplicationTests.java
  src/test/java/com/example/quotesrestapi/UserClassTest.java
Labels: enhancement

#17 Updated Readme
  README.md
Labels: documentation

#19 Minor bug fixes for authentication
  src/main/java/com/example/quotesrestapi/contoller/AuthController.java
  src/main/java/com/example/quotesrestapi/contoller/QuoteAPIController.java
  src/main/java/com/example/quotesrestapi/exceptions/DatabaseException.java
  src/main/java/com/example/quotesrestapi/exceptions/SuperUserClassException.java
  src/main/java/com/example/quotesrestapi/exceptions/UserClassExceptions.java
  src/main/java/com/example/quotesrestapi/model/ResponseTransfer.java
  src/main/java/com/example/quotesrestapi/model/SuperUser.java
  src/main/java/com/example/quotesrestapi/model/User.java
  src/main/java/com/example/quotesrestapi/quoteservice/QuoteService.java
  src/main/java/com/example/quotesrestapi/quoteservice/QuoteServiceImpl.java
  src/main/java/com/example/quotesrestapi/services/DatabaseService.java
  src/test/java/com/example/quotesrestapi/QuoteAPIFunctionTest.java
  src/test/java/com/example/quotesrestapi/UserClassTest.java
Labels: fixed
